# Gradleコマンドで使用するデフォルトのメモリを設定します。ユーザー定義またはコマンドラインプロパティで上書きできます
# Minecraft の逆コンパイル プロセスに十分なメモリを提供するために必要な値
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## 環境プロパティ

# マインクラフトのバージョン
minecraft_version=1.20.4
# マインクラフトのバージョンの範囲
minecraft_version_range=[1.20.4,1.21)
# Forgeのバージョン
forge_version=49.2.0
# Forgeのバージョン範囲は、境界としてForgeの任意のバージョンを使用することも、ローダーのバージョン範囲と一致させることもできます
forge_version_range=[0,)
# ローダーのバージョン範囲は、境界として Forge/FML のメジャーバージョンのみを使用できます
loader_version_range=[0,)
mapping_channel=official
# 上のminecraft_versionと同じにしとけば大丈夫
mapping_version=1.20.4


## modのプロパティ

mod_id=scorpion
mod_name=スコーピオンMod
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.scorpion
mod_authors=ruka
mod_description=スコーピオンを追加するmod